language: rust
rust:
 - stable
os: linux
dist: trusty
sudo: require

env:
  - LIBVIRT=1.2.2  EXT=gz
  - LIBVIRT=2.3.0  EXT=xz
  - LIBVIRT=3.1.0  EXT=xz

install:
  # credit here goes to the go-libvirt authors,
  # see: https://github.com/rgbkrk/libvirt-go/blob/master/.travis.yml
  - sudo apt-get -qqy build-dep libvirt
  - sudo apt-get -qqy install curl qemu-system-x86
  - sudo mkdir -p /usr/src && sudo chown $(id -u) /usr/src
  - curl -O -s https://libvirt.org/sources/libvirt-${LIBVIRT}.tar.${EXT}
  - tar -C /usr/src -xf libvirt-${LIBVIRT}.tar.${EXT}
  - pushd /usr/src/libvirt-${LIBVIRT}
  - |
        ./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc \
                    --without-polkit \
                    --without-esx --without-vbox --without-xen --without-libxl --without-lxc \
                    --with-qemu
  - make
  - sudo make install
  - popd
  - sudo libvirtd -d -l -f libvirtd.conf
  - sudo virtlogd -d || true

script:
  - cargo build --verbose
  - sudo cargo test --verbose
