[package]
name = "libvirt-rpc"
version = "0.1.0"
authors = ["Alexander Polyakov <apolyakov@beget.com>"]
build = "build.rs"

[build-dependencies]
xdrgen = "0.4"

[dependencies]
xdr-codec = { version = "0.4", features = ["bytecodec"] }
byteorder = "1.0"
